"""removing part column from warranty

Revision ID: 0c64afb425fe
Revises: 7abcecd8e01e
Create Date: 2025-03-22 14:27:51.005578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c64afb425fe'
down_revision: Union[str, None] = '7abcecd8e01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fact_warranties_part_id_fkey', 'fact_warranties', type_='foreignkey')
    op.drop_column('fact_warranties', 'part_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_warranties', sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fact_warranties_part_id_fkey', 'fact_warranties', 'dim_parts', ['part_id'], ['part_id'])
    # ### end Alembic commands ###
