"""adding units on Purchase table

Revision ID: 4e29fc7d2a55
Revises: cc86d9a49392
Create Date: 2025-03-22 14:31:19.184097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e29fc7d2a55'
down_revision: Union[str, None] = 'cc86d9a49392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_purchances', sa.Column('units', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_purchances', 'units')
    # ### end Alembic commands ###
