"""adding ondelete and onupdate cascade on supplier fk

Revision ID: 7abcecd8e01e
Revises: 2fd86f7b9a95
Create Date: 2025-03-21 23:24:51.240685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abcecd8e01e'
down_revision: Union[str, None] = '2fd86f7b9a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dim_suppliers_location_id_fkey', 'dim_suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'dim_suppliers', 'dim_locations', ['location_id'], ['location_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dim_suppliers', type_='foreignkey')
    op.create_foreign_key('dim_suppliers_location_id_fkey', 'dim_suppliers', 'dim_locations', ['location_id'], ['location_id'])
    # ### end Alembic commands ###
