"""adding unique constraint in Location

Revision ID: 98db5e0dd4d4
Revises: 4e29fc7d2a55
Create Date: 2025-03-22 19:58:20.901891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98db5e0dd4d4'
down_revision: Union[str, None] = '4e29fc7d2a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_market_country_province', 'dim_locations', ['market', 'country', 'province', 'city'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_country_province', 'dim_locations', type_='unique')
    # ### end Alembic commands ###
