"""adding unit price on Part table

Revision ID: cc86d9a49392
Revises: 0c64afb425fe
Create Date: 2025-03-22 14:30:20.328341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc86d9a49392'
down_revision: Union[str, None] = '0c64afb425fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_parts', sa.Column('unit_price', sa.Double(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_parts', 'unit_price')
    # ### end Alembic commands ###
